3: bgl-ads-2809: 2022-02-08T05:58:43: %ATS-6-INFO: %[pid=835097][pname=MainProcess]: Checking all devices are up and ready is disabled, '--check-all-devices-up' must be set to True in case of pyats runs or '-check_all_devices_up' set to True in case of legacy easypy runs
4: bgl-ads-2809: 2022-02-08T05:58:45: %WARNINGS-4-WARNING: %[part=4.1/3][pid=835097][pname=MainProcess]: /auto/iconatest-bgl/production/hcl/pyats3.6.3/lib/python3.6/site-packages/pyats/topology/device.py:58:
5: bgl-ads-2809: 2022-02-08T05:58:45: %WARNINGS-4-WARNING: %[part=4.2/3][pid=835097][pname=MainProcess]: DeprecationWarning: Device apic-em 'tacacs.username' is deprecated in the testbed YAML.  This key has been moved to device 'credentials'.
6: bgl-ads-2809: 2022-02-08T05:58:45: %WARNINGS-4-WARNING: %[part=4.3/3][pid=835097][pname=MainProcess]:   self._deprecation_check()
7: bgl-ads-2809: 2022-02-08T05:58:45: %WARNINGS-4-WARNING: %[part=7.1/3][pid=835097][pname=MainProcess]: /auto/iconatest-bgl/production/hcl/pyats3.6.3/lib/python3.6/site-packages/pyats/topology/device.py:58:
8: bgl-ads-2809: 2022-02-08T05:58:45: %WARNINGS-4-WARNING: %[part=7.2/3][pid=835097][pname=MainProcess]: DeprecationWarning: Device apic-em 'passwords.linux' is  deprecated in the testbed YAML.  Use 'credentials' instead.
9: bgl-ads-2809: 2022-02-08T05:58:45: %WARNINGS-4-WARNING: %[part=7.3/3][pid=835097][pname=MainProcess]:   self._deprecation_check()
10: bgl-ads-2809: 2022-02-08T05:58:45: %WARNINGS-4-WARNING: %[part=10.1/3][pid=835097][pname=MainProcess]: /auto/iconatest-bgl/production/hcl/pyats3.6.3/lib/python3.6/site-packages/genie/libs/conf/device/__init__.py:49:
11: bgl-ads-2809: 2022-02-08T05:58:45: %WARNINGS-4-WARNING: %[part=10.2/3][pid=835097][pname=MainProcess]: UnsupportedDeviceOsWarning: Device apic-em OS is unknown; Extended Device functionality will not be available: mandatory field 'os' was not given in the yaml file
12: bgl-ads-2809: 2022-02-08T05:58:45: %WARNINGS-4-WARNING: %[part=10.3/3][pid=835097][pname=MainProcess]:   UnsupportedDeviceOsWarning)
13: bgl-ads-2809: 2022-02-08T05:58:45: %WARNINGS-4-WARNING: %[part=13.1/3][pid=835097][pname=MainProcess]: /auto/iconatest-bgl/production/hcl/pyats3.6.3/lib/python3.6/site-packages/genie/libs/conf/device/__init__.py:49:
14: bgl-ads-2809: 2022-02-08T05:58:45: %WARNINGS-4-WARNING: %[part=13.2/3][pid=835097][pname=MainProcess]: UnsupportedDeviceOsWarning: Device ixia OS is unknown; Extended Device functionality will not be available: mandatory field 'os' was not given in the yaml file
15: bgl-ads-2809: 2022-02-08T05:58:45: %WARNINGS-4-WARNING: %[part=13.3/3][pid=835097][pname=MainProcess]:   UnsupportedDeviceOsWarning)
0: bgl-ads-2809: 2022-02-08T05:58:45: %EASYPY-6-INFO: %[pid=835265][pname=Task-1]: Starting task execution: Task-1
1: bgl-ads-2809: 2022-02-08T05:58:45: %EASYPY-6-INFO: %[pid=835265][pname=Task-1]:     test harness = pyats.aetest
2: bgl-ads-2809: 2022-02-08T05:58:45: %EASYPY-6-INFO: %[pid=835265][pname=Task-1]:     testscript   = /ws/viselvar-sjc/DNAC_WiredClient_Auto/northbound/test/wired_client_assurance/wired_client_assurance.py
3: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.1/23][pid=835265][pname=Task-1]: Caught error during task execution: Task-1: wired_client_assurance.py
4: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.2/23][pid=835265][pname=Task-1]: Traceback (most recent call last):
5: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.3/23][pid=835265][pname=Task-1]:   File "/auto/iconatest-bgl/production/hcl/pyats3.6.3/lib/python3.6/site-packages/pyats/aetest/main.py", line 193, in run
6: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.4/23][pid=835265][pname=Task-1]:     reporter = self.reporter)
7: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.5/23][pid=835265][pname=Task-1]:   File "/auto/iconatest-bgl/production/hcl/pyats3.6.3/lib/python3.6/site-packages/pyats/aetest/script.py", line 69, in from_source
8: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.6/23][pid=835265][pname=Task-1]:     module = loader.load(testable)
9: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.7/23][pid=835265][pname=Task-1]:   File "/auto/iconatest-bgl/production/hcl/pyats3.6.3/lib/python3.6/site-packages/pyats/utils/import_utils/flex.py", line 64, in load
10: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.8/23][pid=835265][pname=Task-1]:     module = self.load_module_from_file(obj)
11: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.9/23][pid=835265][pname=Task-1]:   File "/auto/iconatest-bgl/production/hcl/pyats3.6.3/lib/python3.6/site-packages/pyats/utils/import_utils/flex.py", line 117, in load_module_from_file
12: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.10/23][pid=835265][pname=Task-1]:     module = loader.load_module()
13: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.11/23][pid=835265][pname=Task-1]:   File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
14: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.12/23][pid=835265][pname=Task-1]:   File "<frozen importlib._bootstrap_external>", line 823, in load_module
15: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.13/23][pid=835265][pname=Task-1]:   File "<frozen importlib._bootstrap_external>", line 682, in load_module
16: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.14/23][pid=835265][pname=Task-1]:   File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
17: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.15/23][pid=835265][pname=Task-1]:   File "<frozen importlib._bootstrap>", line 684, in _load
18: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.16/23][pid=835265][pname=Task-1]:   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
19: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.17/23][pid=835265][pname=Task-1]:   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
20: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.18/23][pid=835265][pname=Task-1]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
21: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.19/23][pid=835265][pname=Task-1]:   File "/ws/viselvar-sjc/DNAC_WiredClient_Auto/northbound/test/wired_client_assurance/wired_client_assurance.py", line 72, in <module>
22: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.20/23][pid=835265][pname=Task-1]:     from tkinter import Tcl
23: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.21/23][pid=835265][pname=Task-1]:   File "/auto/pysw/cel7x/python64/3.6.4/lib/python3.6/tkinter/__init__.py", line 36, in <module>
24: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.22/23][pid=835265][pname=Task-1]:     import _tkinter # If this fails your Python may not be configured for Tk
25: bgl-ads-2809: 2022-02-08T05:58:47: %EASYPY-3-ERROR: %[part=3.23/23][pid=835265][pname=Task-1]: ImportError: libtk8.4.so: wrong ELF class: ELFCLASS32
16: bgl-ads-2809: 2022-02-08T05:58:48: %EASYPY-6-INFO: %[pid=835097][pname=MainProcess]: TIMS result uploading is not enabled
17: bgl-ads-2809: 2022-02-08T05:58:49: %CISCO-6-INFO: %[pid=835097][pname=MainProcess]: Start Telemetry - Test
18: bgl-ads-2809: 2022-02-08T05:58:51: %CISCO-6-INFO: %[pid=835097][pname=MainProcess]: Posted data to Kafka returning status code 200 within time 0:00:01.227161
19: bgl-ads-2809: 2022-02-08T05:58:51: %CONTRIB-6-INFO: %[pid=835097][pname=MainProcess]: WebEx Token not given as argument or in config. No WebEx notification will be sent
